version: '3'
services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
    command: ["streamlit", "run", "app.py"]